### ISSUE TITLE
Scope 3: Domestic fish consumption

### ISSUE THREAD

**Issue by ignacia-rivera** [camilavargasp/main-fisheries-chile#3]
## Datos de elaboracion de productos SERNAPESCA

Vamos a necesitar clarificar que significan las categorias materia prima, produccion y reproceso en los datos de lineas de elaboracion de SERNAPESCA. Los domcumentos en SERNAPESCA/ Informes y Datos/ Estadisticas/ Elaboracion industrial/ Subsector Elaboracion Industrial.pdf pueden ayudar

**Comment by camilavargasp** [comment]
Podemos hacer un documento con definiciones. 
O si tiene sentido en el mismo Rmd definir cada una de las variables?
